name: Python CI/CD for All Projects

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-path: ${{ fromJson(needs.detect-projects.outputs.project_paths) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install project dependencies
        run: |
          cd ${{ matrix.project-path }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd ${{ matrix.project-path }}
          python -m unittest discover -s . -p "test_*.py"

  detect-projects:
    name: Detect Projects
    runs-on: ubuntu-latest
    outputs:
      project_paths: ${{ steps.set-project-paths.outputs.project_paths }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find project folders
        id: set-project-paths
        run: |
          project_paths=$(find . -type f -name requirements.txt -exec dirname {} \; | jq -R . | jq -s .)
          echo "::set-output name=project_paths::$project_paths"
